# Generated by Django 6.0.5 on 2026-05-24 11:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyGrowthMap',
            fields=[
                ('babygrowthmap_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timecourse', models.BigIntegerField()),
                ('growthrecord', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'babygrowthmap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BabyInformation',
            fields=[
                ('baby_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthdaytime', models.DateTimeField(blank=True, null=True)),
                ('baby_height', models.FloatField(blank=True, null=True)),
                ('baby_weight', models.FloatField(blank=True, null=True)),
                ('babyheadcircumference', models.FloatField(blank=True, null=True)),
                ('chestcircumference', models.FloatField(blank=True, null=True)),
                ('production_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'babyinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BabyRecord',
            fields=[
                ('babyrecord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('record', models.TextField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('headcircumference', models.FloatField(blank=True, null=True)),
                ('chestcircumference', models.FloatField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'babyrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BabyStatus',
            fields=[
                ('babystatus_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'babystatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PregnancyCase',
            fields=[
                ('pregnancycase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menstruation', models.DateField(blank=True, null=True)),
                ('expecteddate', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'pregnancycase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('pregnancyrecord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_date', models.DateTimeField()),
                ('record', models.TextField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pregnancyrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QAConversation',
            fields=[
                ('qa_conversation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'qa_conversation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QAMessage',
            fields=[
                ('serno', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'qa_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'userprofile',
                'managed': False,
            },
        ),
    ]
