# Generated by Django 5.0.3 on 2026-05-31 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyGrowthMap',
            fields=[
                ('babygrowthmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('timecourse', models.SmallIntegerField()),
                ('growthrecord', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'babygrowthmap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BabyInformation',
            fields=[
                ('baby_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('birthdaytime', models.DateTimeField(blank=True, null=True)),
                ('baby_height', models.FloatField(blank=True, null=True)),
                ('baby_weight', models.FloatField(blank=True, null=True)),
                ('babyheadcircumference', models.FloatField(blank=True, null=True)),
                ('chestcircumference', models.FloatField(blank=True, null=True)),
                ('production_method', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'babyinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BabyRecord',
            fields=[
                ('babyrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('record', models.TextField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('headcircumference', models.FloatField(blank=True, null=True)),
                ('chestcircumference', models.FloatField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'babyrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BabyStatus',
            fields=[
                ('babystatus_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'babystatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('carerecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('recordtime', models.DateTimeField()),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'carerecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CareStatus',
            fields=[
                ('carestatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('carestatus', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'carestatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('feeling_id', models.AutoField(primary_key=True, serialize=False)),
                ('feeling_name', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'feeling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalCondition',
            fields=[
                ('physicalcondition_id', models.AutoField(primary_key=True, serialize=False)),
                ('physicalcondition_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'physicalcondition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PregnancyCase',
            fields=[
                ('pregnancycase_id', models.AutoField(primary_key=True, serialize=False)),
                ('menstruation', models.DateField(blank=True, null=True)),
                ('expecteddate', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pregnancycase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('pregnancyrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_date', models.DateTimeField()),
                ('record', models.TextField()),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pregnancyrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prenatalrecord',
            fields=[
                ('prenatalrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('sbp', models.SmallIntegerField(blank=True, null=True)),
                ('dbp', models.SmallIntegerField(blank=True, null=True)),
                ('fetal_heart_rate', models.SmallIntegerField(blank=True, null=True)),
                ('urine_glucose', models.CharField(blank=True, max_length=4, null=True)),
                ('urine_protein', models.CharField(blank=True, max_length=4, null=True)),
                ('edema', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'prenatalrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QAConversation',
            fields=[
                ('qa_conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'qaconversation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QAMessage',
            fields=[
                ('serno', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'qamessage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userfeeling',
            fields=[
                ('userfeeling_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userfeeling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userphysicalcondition',
            fields=[
                ('userphysicalcondition_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userphysicalcondition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('line_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('avatar', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'userprofile',
                'managed': False,
            },
        ),
    ]
