# Generated by Django 6.0.5 on 2026-06-06 19:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyGrowthMap',
            fields=[
                ('babygrowthmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('timecourse', models.SmallIntegerField()),
                ('growthrecord', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'babygrowthmap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BabyInformation',
            fields=[
                ('baby_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('birthdaytime', models.DateTimeField(blank=True, null=True)),
                ('baby_height', models.FloatField(blank=True, null=True)),
                ('baby_weight', models.FloatField(blank=True, null=True)),
                ('babyheadcircumference', models.FloatField(blank=True, null=True)),
                ('chestcircumference', models.FloatField(blank=True, null=True)),
                ('production_method', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'babyinformation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CareStatus',
            fields=[
                ('carestatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('carestatus', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'carestatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('feeling_id', models.AutoField(primary_key=True, serialize=False)),
                ('feeling_name', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'feeling',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhysicalCondition',
            fields=[
                ('physicalcondition_id', models.AutoField(primary_key=True, serialize=False)),
                ('physicalcondition_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'physicalcondition',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PregnancyCase',
            fields=[
                ('pregnancycase_id', models.AutoField(primary_key=True, serialize=False)),
                ('menstruation', models.DateField()),
                ('expecteddate', models.DateField()),
                ('code', models.CharField(max_length=255, unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pregnancycase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('pregnancyrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_date', models.DateTimeField()),
                ('record', models.TextField()),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pregnancyrecord',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QAConversation',
            fields=[
                ('qaconversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'qaconversation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('line_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('avatar', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'userprofile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BabyRecord',
            fields=[
                ('babyrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('record', models.TextField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('headcircumference', models.FloatField(blank=True, null=True)),
                ('chestcircumference', models.FloatField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.babyinformation')),
            ],
            options={
                'db_table': 'babyrecord',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BabyStatus',
            fields=[
                ('babystatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('babygrowthmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.babygrowthmap')),
                ('babyrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.babyrecord')),
            ],
            options={
                'db_table': 'babystatus',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='babyinformation',
            name='pregnancycase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregnancycase'),
        ),
        migrations.CreateModel(
            name='Prenatalrecord',
            fields=[
                ('prenatalrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('sbp', models.SmallIntegerField(blank=True, null=True)),
                ('dbp', models.SmallIntegerField(blank=True, null=True)),
                ('fetal_heart_rate', models.SmallIntegerField(blank=True, null=True)),
                ('urine_glucose', models.CharField(blank=True, max_length=4, null=True)),
                ('urine_protein', models.CharField(blank=True, max_length=4, null=True)),
                ('edema', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('pregnancyrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregnancyrecord', unique=True)),
            ],
            options={
                'db_table': 'prenatalrecord',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QAMessage',
            fields=[
                ('serno', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('qa_conversation', models.ForeignKey(db_column='qaconversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.qaconversation')),
            ],
            options={
                'db_table': 'qamessage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userfeeling',
            fields=[
                ('userfeeling_id', models.AutoField(primary_key=True, serialize=False)),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feeling')),
                ('pregnancyrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregnancyrecord')),
            ],
            options={
                'db_table': 'userfeeling',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userphysicalcondition',
            fields=[
                ('userphysicalcondition_id', models.AutoField(primary_key=True, serialize=False)),
                ('physicalcondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.physicalcondition')),
                ('pregnancyrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregnancyrecord')),
            ],
            options={
                'db_table': 'userphysicalcondition',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='qaconversation',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='pregnancyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='pregnancycase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('familymember_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=5)),
                ('join_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pregnancycase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregnancycase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'db_table': 'familymember',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('carerecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('recordtime', models.DateTimeField()),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField()),
                ('carestatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carestatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'db_table': 'carerecord',
                'managed': True,
            },
        ),
    ]
