# Generated by Django 5.0.3 on 2026-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAConversation',
            fields=[
                ('qa_conversation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'qa_conversation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QAMessage',
            fields=[
                ('serno', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'qa_message',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='qaanswer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qaquestion',
            options={'managed': False},
        ),
    ]
