# Generated by Django 6.0.5 on 2026-06-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancyrecord',
            name='check_date',
            field=models.DateField(),
        ),
    ]
