# Generated by Django 6.0.5 on 2026-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('feeling_id', models.AutoField(primary_key=True, serialize=False)),
                ('feeling_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'feeling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalCondition',
            fields=[
                ('physicalcondition_id', models.AutoField(db_column='physicalcondition_id', primary_key=True, serialize=False)),
                ('physicalcondition_name', models.CharField(db_column='physicalcondition_name', max_length=255)),
            ],
            options={
                'db_table': 'physicalcondition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prenatalrecord',
            fields=[
                ('prenatalrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('sbp', models.SmallIntegerField()),
                ('dbp', models.SmallIntegerField()),
                ('fetal_heart_rate', models.SmallIntegerField()),
                ('urine_glucose', models.CharField(max_length=4)),
                ('urine_protein', models.CharField(max_length=4)),
                ('edema', models.CharField(max_length=4)),
                ('photo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prenatalrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userfeeling',
            fields=[
                ('userfeeling_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userfeeling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userphysicalcondition',
            fields=[
                ('userphysicalcondition_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userphysicalcondition',
                'managed': False,
            },
        ),
    ]
