# Generated by Django 6.0.5 on 2026-05-19 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_qaconversation_qamessage_alter_qaanswer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BabyInformation",
            fields=[
                ("baby_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("birthdaytime", models.DateTimeField(blank=True, null=True)),
                ("baby_height", models.FloatField(blank=True, null=True)),
                ("baby_weight", models.FloatField(blank=True, null=True)),
                ("babyheadcircumference", models.FloatField(blank=True, null=True)),
                ("chestcircumference", models.FloatField(blank=True, null=True)),
                (
                    "production_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "babyinformation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BabyRecord",
            fields=[
                (
                    "babyrecord_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("record", models.TextField()),
                ("weight", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("headcircumference", models.FloatField(blank=True, null=True)),
                ("chestcircumference", models.FloatField(blank=True, null=True)),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "babyrecord",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PregnancyCase",
            fields=[
                (
                    "pregnancycase_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("menstruation", models.DateField(blank=True, null=True)),
                ("expecteddate", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=255, unique=True)),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "pregnancycase",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PregnancyRecord",
            fields=[
                (
                    "pregnancyrecord_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("check_date", models.DateTimeField()),
                ("record", models.TextField()),
                ("weight", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "pregnancyrecord",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="QAAnswer",
        ),
        migrations.DeleteModel(
            name="QAQuestion",
        ),
    ]
