# Generated by Django 6.0.5 on 2026-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_babyinformation_babyrecord_pregnancycase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BabyGrowthMap",
            fields=[
                (
                    "babygrowthmap_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("timecourse", models.BigIntegerField()),
                ("growthrecord", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "babygrowthmap",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BabyStatus",
            fields=[
                (
                    "babystatus_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "babystatus",
                "managed": False,
            },
        ),
    ]
