tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tertiary-fixed-variant": "#6c3f51",
                "secondary": "#2f6275",
                "surface-dim": "#d4d5d1",
                "on-surface": "#2e2f2d",
                "on-primary": "#f8efff",
                "background": "#f7f6f3",
                "surface-bright": "#f7f6f3",
                "on-secondary-fixed-variant": "#2b5e71",
                "tertiary-fixed-dim": "#e9aec3",
                "on-tertiary": "#ffeff2",
                "secondary-fixed-dim": "#a4d6ed",
                "secondary-fixed": "#b2e4fb",
                "surface-tint": "#65518a",
                "on-tertiary-fixed": "#4b2334",
                "tertiary-container": "#f8bbd0",
                "tertiary-fixed": "#f8bbd0",
                "inverse-surface": "#0d0f0d",
                "error-dim": "#a70138",
                "error-container": "#f74b6d",
                "on-primary-fixed": "#362459",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#ddddd9",
                "on-secondary-container": "#1f5467",
                "surface-container-high": "#e3e3df",
                "outline-variant": "#adadab",
                "primary-fixed-dim": "#c8b1f0",
                "primary-container": "#d6beff",
                "tertiary": "#7d4d5f",
                "surface-variant": "#ddddd9",
                "on-primary-container": "#4b386e",
                "outline": "#767775",
                "surface-container-low": "#f1f1ee",
                "inverse-primary": "#d6beff",
                "tertiary-dim": "#6f4253",
                "surface-container": "#e8e8e5",
                "inverse-on-surface": "#9d9d9a",
                "on-secondary-fixed": "#014154",
                "surface": "#f7f6f3",
                "on-tertiary-container": "#623648",
                "on-secondary": "#e4f5ff",
                "on-background": "#2e2f2d",
                "on-error-container": "#510017",
                "on-error": "#ffefef",
                "on-surface-variant": "#5b5c5a",
                "secondary-container": "#b2e4fb",
                "secondary-dim": "#215669",
                "primary-fixed": "#d6beff",
                "on-primary-fixed-variant": "#544178",
                "error": "#b41340",
                "primary": "#65518a",
                "primary-dim": "#59467d"
            },
            "borderRadius": {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Be Vietnam Pro"],
                "label": ["Be Vietnam Pro"]
            }
        },
    },
};
