import os
import re

files = [
    "pregnancyrecord.html",
    "pregnancyrecord_new copy.html",
    "babyinformation.html",
    "babyinformation_empty.html"
]

calendar_trigger_regex = re.compile(
    r'<div class="relative inline-flex items-center cursor-pointer group hover:bg-primary/5 px-4 py-2 -ml-4 rounded-2xl transition-colors"[^>]*>.*?<h2[^>]*>\s*(\d{4}年\s*\d+月)\s*<span[^>]*>keyboard_arrow_down</span>\s*</h2>\s*</div>',
    re.DOTALL
)

modal_html = """
    <!-- Custom Month Picker Modal -->
    <div id="month-picker-modal" class="fixed inset-0 z-[60] flex items-end sm:items-center justify-center opacity-0 pointer-events-none transition-all duration-300">
        <!-- Backdrop -->
        <div id="month-picker-backdrop" class="absolute inset-0 bg-on-surface/40 backdrop-blur-sm transition-opacity duration-300"></div>
        
        <!-- Modal Content -->
        <div id="month-picker-content" class="relative w-full max-w-md bg-surface-container-lowest rounded-t-[2rem] sm:rounded-3xl shadow-2xl transform translate-y-full sm:translate-y-4 sm:scale-95 transition-all duration-300 flex flex-col sm:mb-4">
            <!-- Handle for mobile -->
            <div class="w-full flex justify-center pt-3 pb-1 sm:hidden">
                <div class="w-12 h-1.5 bg-outline-variant/30 rounded-full"></div>
            </div>
            
            <div class="p-4 border-b border-surface-container-high/50 flex justify-between items-center shrink-0">
                <button type="button" id="month-picker-prev-year" class="p-2 hover:bg-surface-container-low rounded-full transition-colors cursor-pointer text-on-surface-variant">
                    <span class="material-symbols-outlined">chevron_left</span>
                </button>
                <h3 id="month-picker-year-display" class="font-headline font-bold text-lg text-primary">2024年</h3>
                <button type="button" id="month-picker-next-year" class="p-2 hover:bg-surface-container-low rounded-full transition-colors cursor-pointer text-on-surface-variant">
                    <span class="material-symbols-outlined">chevron_right</span>
                </button>
            </div>
            
            <div class="p-6 grid grid-cols-4 gap-4" id="month-picker-grid">
                <!-- Months will be generated by JS -->
            </div>
            
            <div class="p-4 border-t border-surface-container-high/50 flex justify-end gap-3 items-center shrink-0">
                <button type="button" id="close-month-picker" class="px-6 py-2 rounded-full font-bold text-on-surface-variant hover:bg-surface-container-low transition-colors cursor-pointer">
                    取消
                </button>
                <button type="button" id="confirm-month-picker" class="px-6 py-2 rounded-full font-bold bg-primary text-white shadow-lg shadow-primary/30 hover:scale-[1.02] active:scale-95 transition-all cursor-pointer">
                    確定
                </button>
            </div>
        </div>
    </div>
"""

script_html = """
    <!-- Custom Month Picker Script -->
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const monthPickerModal = document.getElementById('month-picker-modal');
            const monthPickerBackdrop = document.getElementById('month-picker-backdrop');
            const monthPickerContent = document.getElementById('month-picker-content');
            const closeMonthPicker = document.getElementById('close-month-picker');
            const confirmMonthPicker = document.getElementById('confirm-month-picker');
            const monthPickerYearDisplay = document.getElementById('month-picker-year-display');
            const monthPickerGrid = document.getElementById('month-picker-grid');
            const prevYearBtn = document.getElementById('month-picker-prev-year');
            const nextYearBtn = document.getElementById('month-picker-next-year');
            const customDatePickerBtn = document.getElementById('custom-date-picker-btn');
            const customDatePickerText = document.getElementById('custom-date-picker-text');

            if (!monthPickerModal || !customDatePickerBtn) return;

            let currentSelectedYear = 2024;
            let currentSelectedMonth = 5;
            
            // Try to parse initial value from text
            const initialText = customDatePickerText.innerText;
            const match = initialText.match(/(\\d{4})年\\s*(\\d+)月/);
            if (match) {
                currentSelectedYear = parseInt(match[1]);
                currentSelectedMonth = parseInt(match[2]);
            }

            let tempYear = currentSelectedYear;
            let tempMonth = currentSelectedMonth;

            function renderMonthGrid() {
                monthPickerGrid.innerHTML = '';
                for (let i = 1; i <= 12; i++) {
                    const btn = document.createElement('button');
                    btn.type = 'button';
                    // Base classes
                    btn.className = 'py-3 rounded-xl text-sm font-bold transition-all cursor-pointer border ';
                    if (tempYear === currentSelectedYear && i === tempMonth) {
                        btn.className += 'bg-primary text-white shadow-md border-primary';
                    } else if (tempMonth === i) {
                        btn.className += 'bg-primary/10 text-primary border-primary/20';
                    } else {
                        btn.className += 'bg-surface-container-lowest text-on-surface hover:bg-surface-container-low border-surface-container-high';
                    }
                    btn.innerText = `${i}月`;
                    btn.onclick = () => {
                        tempMonth = i;
                        renderMonthGrid();
                    };
                    monthPickerGrid.appendChild(btn);
                }
            }

            function openMonthPicker() {
                tempYear = currentSelectedYear;
                tempMonth = currentSelectedMonth;
                monthPickerYearDisplay.innerText = `${tempYear}年`;
                renderMonthGrid();
                
                monthPickerModal.classList.remove('opacity-0', 'pointer-events-none');
                monthPickerModal.classList.add('opacity-100', 'pointer-events-auto');
                setTimeout(() => {
                    monthPickerContent.classList.remove('translate-y-full', 'sm:translate-y-4', 'sm:scale-95');
                    monthPickerContent.classList.add('translate-y-0', 'sm:translate-y-0', 'sm:scale-100');
                }, 10);
            }

            function closeMonthPickerModal() {
                monthPickerContent.classList.remove('translate-y-0', 'sm:translate-y-0', 'sm:scale-100');
                monthPickerContent.classList.add('translate-y-full', 'sm:translate-y-4', 'sm:scale-95');
                setTimeout(() => {
                    monthPickerModal.classList.remove('opacity-100', 'pointer-events-auto');
                    monthPickerModal.classList.add('opacity-0', 'pointer-events-none');
                }, 300);
            }

            customDatePickerBtn.addEventListener('click', openMonthPicker);
            closeMonthPicker.addEventListener('click', closeMonthPickerModal);
            monthPickerBackdrop.addEventListener('click', closeMonthPickerModal);
            
            confirmMonthPicker.addEventListener('click', () => {
                currentSelectedYear = tempYear;
                currentSelectedMonth = tempMonth;
                customDatePickerText.innerHTML = `${currentSelectedYear}年 ${currentSelectedMonth}月 <span class="material-symbols-outlined text-primary ml-1">keyboard_arrow_down</span>`;
                closeMonthPickerModal();
            });

            prevYearBtn.addEventListener('click', () => {
                tempYear--;
                monthPickerYearDisplay.innerText = `${tempYear}年`;
                renderMonthGrid();
            });

            nextYearBtn.addEventListener('click', () => {
                tempYear++;
                monthPickerYearDisplay.innerText = `${tempYear}年`;
                renderMonthGrid();
            });
        });
    </script>
"""

for file in files:
    if not os.path.exists(file):
        print(f"Skipping {file}, not found")
        continue

    with open(file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Check if we already injected
    if 'id="month-picker-modal"' in content:
        print(f"Already injected into {file}")
        continue

    # 1. Replace the trigger
    def replacer(match):
        date_text = match.group(1)
        return f"""<div id="custom-date-picker-btn" class="relative inline-flex items-center cursor-pointer group hover:bg-primary/5 px-4 py-2 -ml-4 rounded-2xl transition-colors">
                    <h2 id="custom-date-picker-text" class="text-primary font-extrabold text-2xl tracking-tight flex items-center gap-1 relative z-0">
                        {date_text}
                        <span class="material-symbols-outlined text-primary ml-1">keyboard_arrow_down</span>
                    </h2>
                </div>"""

    new_content = calendar_trigger_regex.sub(replacer, content)

    # 2. Inject Modal HTML just before </body>
    if '</body>' in new_content:
        new_content = new_content.replace('</body>', f"{modal_html}\n{script_html}\n</body>")

    with open(file, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"Updated {file}")
